@baseUrl = http://localhost:3000

###Register an existing user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username": "asox",
    "password":"Ylann", 
    "email":"ylann@vinci.be", 
    "nom":"Mommens", 
    "prenom":"Ylann"
}

###Register a new user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username": "tester",
    "password":"azerty123", 
    "email":"tester@gmail.com", 
    "nom":"tester", 
    "prenom":"tester"
}

###Login existing user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"asox",
    "password":"OdWqQm8nKvFqni9"
}

###Login an non existing user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"newff",
    "password":"newnewnew"
}
